In [1]:
import numpy as np
from Strassen import strassen
from AI_mul import ai
from Binet import binet

In [2]:
def random_matrix(n):
    return np.random.uniform(0.00000001, 1, (n, n))

In [3]:
mat = random_matrix(4)

In [4]:
print(mat)

[[0.92234028 0.43327447 0.54836177 0.3542006 ]
 [0.67647587 0.02454961 0.42955905 0.89790927]
 [0.26025424 0.21811821 0.97008481 0.17207262]
 [0.00763498 0.6876607  0.89213164 0.2736142 ]]


In [5]:
print(binet(mat, mat))

[[1.2892291  0.77344074 1.5398441  0.907007  ]
 [0.75919825 1.00485398 1.59926099 0.58124756]
 [0.64137714 0.44803698 1.33098409 0.50203912]
 [0.70649801 0.40293374 1.40912085 0.84853739]]


In [6]:
print(mat @ mat)

[[1.2892291  0.77344074 1.5398441  0.907007  ]
 [0.75919825 1.00485398 1.59926099 0.58124756]
 [0.64137714 0.44803698 1.33098409 0.50203912]
 [0.70649801 0.40293374 1.40912085 0.84853739]]


In [7]:
print(strassen(mat, mat))

[[1.2892291  0.77344074 1.5398441  0.907007  ]
 [0.75919825 1.00485398 1.59926099 0.58124756]
 [0.64137714 0.44803698 1.33098409 0.50203912]
 [0.70649801 0.40293374 1.40912085 0.84853739]]
